### ISSUE TITLE
How to create a bootable Windows USB using Rufus

### ISSUE THREAD

**Issue by rudiansyah1996** [jpnix/burn2flash#1]
A few years ago the windows installation process was done using a CD. With increasingly sophisticated and many new discoveries, there is now an easier and simpler way to install Os windows using RUFUSH.

Rufus supports bootable USB for many operating systems, including Windows and Linux operating systems. Some uses of this rufus software:
* Create USB installation media from bootable ISO (Windows, Linux, UEFI and others)
* Helps buddies who need to work on systems that do not have OS installed.
* Helps buddy who needs to flash BIOS or other firmware from DOS.

Before installing os first we create Bootable usb windows 7 Ultimate Sp1 x64 via rufush, this will be the tutorial on my article.

Materials needed:
1. **<a href='https://rufus.akeo.ie/'>Rufush</a>**
2. **<a href='https://www.microsoft.com/en-us/software-download/windows7'>Iso Image Windows 7 Ultimate Sp1 x64</a>**

Here are the steps to create a Bootable usb Windows 7 with Rufush:
1. first step you must prepare rufush software and iso image of Windows 7 Ultimate Sp1 x64 first.
2. Make sure that your Usb is installed correctly.
3. Next run rufush software that you have prepared earlier.
![1](https://user-images.githubusercontent.com/34920529/34463185-8cc4e042-ee86-11e7-97a6-f2d575810077.png)

4. Select the connected Usb and select the iso image browser.
![2](https://user-images.githubusercontent.com/34920529/34463208-efc1147c-ee86-11e7-92aa-0906d8b1aa6a.png)

5. Select the iso image windows 7 Ultimate Sp1 x64.
![3](https://user-images.githubusercontent.com/34920529/34463211-ffb03cd2-ee86-11e7-9449-c64d2891d736.png)

6. After the iso file is selected directly click start.
![4](https://user-images.githubusercontent.com/34920529/34463219-142a27e0-ee87-11e7-9a5c-0947355f23e1.png)

7. Next warning warning appears, and click okay.
![5](https://user-images.githubusercontent.com/34920529/34463222-22308a46-ee87-11e7-8ea5-3f61b1ac006c.png)

8. Wait until the process is complete.
![6](https://user-images.githubusercontent.com/34920529/34463227-42be0bf8-ee87-11e7-98e6-a19edab5bb40.png)

9. If the display is like the picture below, means the process of making bootable windows 7 Ultimate Sp1 x64 is complete and can be directly used to install Os windows on your computer.
![7](https://user-images.githubusercontent.com/34920529/34463231-4e26b760-ee87-11e7-85e2-9d3cfd476a46.png)

That was a little tutorial from me about making Bootable windosw through rufush.
If anything is unclear can you leave a comment in the comment field.
That is all and thank you.

**Comment by jpnix** [comment]
Thanks for the tutorial. I wrote this script a long time ago actually to make bootable media from Unix based operating systems.
